version: "3.8"

services: 
  localstack: 
    container_name: localstack_container
    image: localstack/localstack:3.8.1
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_data:

# docker compose up -d
# docker ps
